package com.alpware.keymapkit.layout

import com.alpware.keymapkit.R

enum class LayoutCategory { LATIN, CYRILLIC, ARABIC, INDIC, ASIAN, SEMITIC, AFRICAN }

data class KeyboardLayoutItem(
    val id: String,
    val labelRes: Int,
    val receiverClassName: String,
    val category: LayoutCategory,
    val popular: Boolean = false,
)

object KeyboardLayoutCatalog {
    val all: List<KeyboardLayoutItem> = listOf(
        KeyboardLayoutItem("abc", R.string.layout_abc, "com.alpware.keymapkit.receiver.generated.AbcLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("albanian", R.string.layout_albanian, "com.alpware.keymapkit.receiver.generated.AlbanianLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("arabic_102_azerty", R.string.layout_arabic_102_azerty, "com.alpware.keymapkit.receiver.generated.Arabic102AzertyLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("armenian_phonetic", R.string.layout_armenian_phonetic, "com.alpware.keymapkit.receiver.generated.ArmenianPhoneticLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("armenian_typewriter", R.string.layout_armenian_typewriter, "com.alpware.keymapkit.receiver.generated.ArmenianTypewriterLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("assamese_inscript", R.string.layout_assamese_inscript, "com.alpware.keymapkit.receiver.generated.AssameseInscriptLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("azeri_cyrillic", R.string.layout_azeri_cyrillic, "com.alpware.keymapkit.receiver.generated.AzeriCyrillicLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("azeri_latin", R.string.layout_azeri_latin, "com.alpware.keymapkit.receiver.generated.AzeriLatinLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("bangla_jatiya_layout", R.string.layout_bangla_jatiya_layout, "com.alpware.keymapkit.receiver.generated.BanglaJatiyaLayoutLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("bangla_probhat_layout", R.string.layout_bangla_probhat_layout, "com.alpware.keymapkit.receiver.generated.BanglaProbhatLayoutLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("bashkir", R.string.layout_bashkir, "com.alpware.keymapkit.receiver.generated.BashkirLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("belarusian", R.string.layout_belarusian, "com.alpware.keymapkit.receiver.generated.BelarusianLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("belgian_comma", R.string.layout_belgian_comma, "com.alpware.keymapkit.receiver.generated.BelgianCommaLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("belgian_french", R.string.layout_belgian_french, "com.alpware.keymapkit.receiver.generated.BelgianFrenchLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("belgian_period", R.string.layout_belgian_period, "com.alpware.keymapkit.receiver.generated.BelgianPeriodLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("bengali", R.string.layout_bengali, "com.alpware.keymapkit.receiver.generated.BengaliLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("bengali_inscript", R.string.layout_bengali_inscript, "com.alpware.keymapkit.receiver.generated.BengaliInscriptLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("bosnian_cyrillic", R.string.layout_bosnian_cyrillic, "com.alpware.keymapkit.receiver.generated.BosnianCyrillicLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("bulgarian_latin", R.string.layout_bulgarian_latin, "com.alpware.keymapkit.receiver.generated.BulgarianLatinLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("bulgarian_phonetic", R.string.layout_bulgarian_phonetic, "com.alpware.keymapkit.receiver.generated.BulgarianPhoneticLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("bulgarian_phonetic_traditional", R.string.layout_bulgarian_phonetic_traditional, "com.alpware.keymapkit.receiver.generated.BulgarianPhoneticTraditionalLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("bulgarian_typewriter", R.string.layout_bulgarian_typewriter, "com.alpware.keymapkit.receiver.generated.BulgarianTypewriterLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("canadian_french", R.string.layout_canadian_french, "com.alpware.keymapkit.receiver.generated.CanadianFrenchLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("canadian_multilingual_standard", R.string.layout_canadian_multilingual_standard, "com.alpware.keymapkit.receiver.generated.CanadianMultilingualStandardLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("cherokee_nation", R.string.layout_cherokee_nation, "com.alpware.keymapkit.receiver.generated.CherokeeNationLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("colemak", R.string.layout_colemak, "com.alpware.keymapkit.receiver.generated.ColemakLayoutReceiver", LayoutCategory.LATIN, true),
        KeyboardLayoutItem("colemak_mod_dh", R.string.layout_colemak_mod_dh, "com.alpware.keymapkit.receiver.generated.ColemakModDhLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("czech_programmers", R.string.layout_czech_programmers, "com.alpware.keymapkit.receiver.generated.CzechProgrammersLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("czech_qwerty", R.string.layout_czech_qwerty, "com.alpware.keymapkit.receiver.generated.CzechQwertyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("czech_qwertz", R.string.layout_czech_qwertz, "com.alpware.keymapkit.receiver.generated.CzechQwertzLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("devanagari_inscript", R.string.layout_devanagari_inscript, "com.alpware.keymapkit.receiver.generated.DevanagariInscriptLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("divehi_phonetic", R.string.layout_divehi_phonetic, "com.alpware.keymapkit.receiver.generated.DivehiPhoneticLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("divehi_typewriter", R.string.layout_divehi_typewriter, "com.alpware.keymapkit.receiver.generated.DivehiTypewriterLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("dutch", R.string.layout_dutch, "com.alpware.keymapkit.receiver.generated.DutchLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("english_india", R.string.layout_english_india, "com.alpware.keymapkit.receiver.generated.EnglishIndiaLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("eu_eurkey", R.string.layout_eu_eurkey, "com.alpware.keymapkit.receiver.generated.EuEurkeyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("faeroese", R.string.layout_faeroese, "com.alpware.keymapkit.receiver.generated.FaeroeseLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("finnish_with_sami", R.string.layout_finnish_with_sami, "com.alpware.keymapkit.receiver.generated.FinnishWithSamiLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("georgian_ergonomic", R.string.layout_georgian_ergonomic, "com.alpware.keymapkit.receiver.generated.GeorgianErgonomicLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("georgian_mes", R.string.layout_georgian_mes, "com.alpware.keymapkit.receiver.generated.GeorgianMesLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("georgian_qwerty", R.string.layout_georgian_qwerty, "com.alpware.keymapkit.receiver.generated.GeorgianQwertyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("german_ibm", R.string.layout_german_ibm, "com.alpware.keymapkit.receiver.generated.GermanIbmLayoutReceiver", LayoutCategory.LATIN, true),
        KeyboardLayoutItem("greek_220", R.string.layout_greek_220, "com.alpware.keymapkit.receiver.generated.Greek220LayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("greek_220_latin", R.string.layout_greek_220_latin, "com.alpware.keymapkit.receiver.generated.Greek220LatinLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("greek_319_latin", R.string.layout_greek_319_latin, "com.alpware.keymapkit.receiver.generated.Greek319LatinLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("greek_latin", R.string.layout_greek_latin, "com.alpware.keymapkit.receiver.generated.GreekLatinLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("greenlandic", R.string.layout_greenlandic, "com.alpware.keymapkit.receiver.generated.GreenlandicLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("gujarati", R.string.layout_gujarati, "com.alpware.keymapkit.receiver.generated.GujaratiLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("halmak", R.string.layout_halmak, "com.alpware.keymapkit.receiver.generated.HalmakLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("hausa", R.string.layout_hausa, "com.alpware.keymapkit.receiver.generated.HausaLayoutReceiver", LayoutCategory.AFRICAN, false),
        KeyboardLayoutItem("hawaiian", R.string.layout_hawaiian, "com.alpware.keymapkit.receiver.generated.HawaiianLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("hebrew_standard", R.string.layout_hebrew_standard, "com.alpware.keymapkit.receiver.generated.HebrewStandardLayoutReceiver", LayoutCategory.SEMITIC, false),
        KeyboardLayoutItem("hindi_traditional", R.string.layout_hindi_traditional, "com.alpware.keymapkit.receiver.generated.HindiTraditionalLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("hungarian_101_key_qwerty", R.string.layout_hungarian_101_key_qwerty, "com.alpware.keymapkit.receiver.generated.Hungarian101KeyQwertyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("inuktitut_latin", R.string.layout_inuktitut_latin, "com.alpware.keymapkit.receiver.generated.InuktitutLatinLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("irish", R.string.layout_irish, "com.alpware.keymapkit.receiver.generated.IrishLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("italian_142", R.string.layout_italian_142, "com.alpware.keymapkit.receiver.generated.Italian142LayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("jawi_phonetic_qwerty", R.string.layout_jawi_phonetic_qwerty, "com.alpware.keymapkit.receiver.generated.JawiPhoneticQwertyLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("jawi_sirim", R.string.layout_jawi_sirim, "com.alpware.keymapkit.receiver.generated.JawiSirimLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("kannada", R.string.layout_kannada, "com.alpware.keymapkit.receiver.generated.KannadaLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("kazakh", R.string.layout_kazakh, "com.alpware.keymapkit.receiver.generated.KazakhLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("khmer", R.string.layout_khmer, "com.alpware.keymapkit.receiver.generated.KhmerLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("khmer_nida", R.string.layout_khmer_nida, "com.alpware.keymapkit.receiver.generated.KhmerNidaLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("korean", R.string.layout_korean, "com.alpware.keymapkit.receiver.generated.KoreanLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("kurdish_krg", R.string.layout_kurdish_krg, "com.alpware.keymapkit.receiver.generated.KurdishKrgLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("kurdish_sorani_hejar", R.string.layout_kurdish_sorani_hejar, "com.alpware.keymapkit.receiver.generated.KurdishSoraniHejarLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("kyrgyz_cyrillic", R.string.layout_kyrgyz_cyrillic, "com.alpware.keymapkit.receiver.generated.KyrgyzCyrillicLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("lao", R.string.layout_lao, "com.alpware.keymapkit.receiver.generated.LaoLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("latin_american", R.string.layout_latin_american, "com.alpware.keymapkit.receiver.generated.LatinAmericanLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("latvian_qwerty", R.string.layout_latvian_qwerty, "com.alpware.keymapkit.receiver.generated.LatvianQwertyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("lisu_basic", R.string.layout_lisu_basic, "com.alpware.keymapkit.receiver.generated.LisuBasicLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("lisu_standard", R.string.layout_lisu_standard, "com.alpware.keymapkit.receiver.generated.LisuStandardLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("lithuanian_ibm", R.string.layout_lithuanian_ibm, "com.alpware.keymapkit.receiver.generated.LithuanianIbmLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("lithuanian_standard", R.string.layout_lithuanian_standard, "com.alpware.keymapkit.receiver.generated.LithuanianStandardLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("luxembourgish", R.string.layout_luxembourgish, "com.alpware.keymapkit.receiver.generated.LuxembourgishLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("macedonian_fyrom", R.string.layout_macedonian_fyrom, "com.alpware.keymapkit.receiver.generated.MacedonianFyromLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("macedonian_fyrom_standard", R.string.layout_macedonian_fyrom_standard, "com.alpware.keymapkit.receiver.generated.MacedonianFyromStandardLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("malayalam", R.string.layout_malayalam, "com.alpware.keymapkit.receiver.generated.MalayalamLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("maltese_47_key", R.string.layout_maltese_47_key, "com.alpware.keymapkit.receiver.generated.Maltese47KeyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("maltese_48_key", R.string.layout_maltese_48_key, "com.alpware.keymapkit.receiver.generated.Maltese48KeyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("maori", R.string.layout_maori, "com.alpware.keymapkit.receiver.generated.MaoriLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("marathi", R.string.layout_marathi, "com.alpware.keymapkit.receiver.generated.MarathiLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("mongolian_cyrillic", R.string.layout_mongolian_cyrillic, "com.alpware.keymapkit.receiver.generated.MongolianCyrillicLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("mongolian_mongolian_script", R.string.layout_mongolian_mongolian_script, "com.alpware.keymapkit.receiver.generated.MongolianMongolianScriptLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("myanmar", R.string.layout_myanmar, "com.alpware.keymapkit.receiver.generated.MyanmarLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("n_ko", R.string.layout_n_ko, "com.alpware.keymapkit.receiver.generated.NKoLayoutReceiver", LayoutCategory.AFRICAN, false),
        KeyboardLayoutItem("neo2", R.string.layout_neo2, "com.alpware.keymapkit.receiver.generated.Neo2LayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("nepali", R.string.layout_nepali, "com.alpware.keymapkit.receiver.generated.NepaliLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("new_tai_lue", R.string.layout_new_tai_lue, "com.alpware.keymapkit.receiver.generated.NewTaiLueLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("nias", R.string.layout_nias, "com.alpware.keymapkit.receiver.generated.NiasLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("norwegian_with_sami", R.string.layout_norwegian_with_sami, "com.alpware.keymapkit.receiver.generated.NorwegianWithSamiLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("odia", R.string.layout_odia, "com.alpware.keymapkit.receiver.generated.OdiaLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("ogham", R.string.layout_ogham, "com.alpware.keymapkit.receiver.generated.OghamLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("pashto_afghanistan", R.string.layout_pashto_afghanistan, "com.alpware.keymapkit.receiver.generated.PashtoAfghanistanLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("persian_standard", R.string.layout_persian_standard, "com.alpware.keymapkit.receiver.generated.PersianStandardLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("phags_pa", R.string.layout_phags_pa, "com.alpware.keymapkit.receiver.generated.PhagsPaLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("polish_programmers", R.string.layout_polish_programmers, "com.alpware.keymapkit.receiver.generated.PolishProgrammersLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("portuguese_magic", R.string.layout_portuguese_magic, "com.alpware.keymapkit.receiver.generated.PortugueseMagicLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("punjabi", R.string.layout_punjabi, "com.alpware.keymapkit.receiver.generated.PunjabiLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("romanian_programmers", R.string.layout_romanian_programmers, "com.alpware.keymapkit.receiver.generated.RomanianProgrammersLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("romanian_standard", R.string.layout_romanian_standard, "com.alpware.keymapkit.receiver.generated.RomanianStandardLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("russian_phonetic_linux", R.string.layout_russian_phonetic_linux, "com.alpware.keymapkit.receiver.generated.RussianPhoneticLinuxLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("russian_phonetic_yawert_winrus_com", R.string.layout_russian_phonetic_yawert_winrus_com, "com.alpware.keymapkit.receiver.generated.RussianPhoneticYawertWinrusComLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("russian_typewriter", R.string.layout_russian_typewriter, "com.alpware.keymapkit.receiver.generated.RussianTypewriterLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("sakha", R.string.layout_sakha, "com.alpware.keymapkit.receiver.generated.SakhaLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("sami_extended_finland_sweden", R.string.layout_sami_extended_finland_sweden, "com.alpware.keymapkit.receiver.generated.SamiExtendedFinlandSwedenLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("sami_extended_norway", R.string.layout_sami_extended_norway, "com.alpware.keymapkit.receiver.generated.SamiExtendedNorwayLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("santali_inscript", R.string.layout_santali_inscript, "com.alpware.keymapkit.receiver.generated.SantaliInscriptLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("santali_sarjom_baha_phonetic", R.string.layout_santali_sarjom_baha_phonetic, "com.alpware.keymapkit.receiver.generated.SantaliSarjomBahaPhoneticLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("scottish_gaelic", R.string.layout_scottish_gaelic, "com.alpware.keymapkit.receiver.generated.ScottishGaelicLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("serbian_cyrillic", R.string.layout_serbian_cyrillic, "com.alpware.keymapkit.receiver.generated.SerbianCyrillicLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("serbian_latin", R.string.layout_serbian_latin, "com.alpware.keymapkit.receiver.generated.SerbianLatinLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("sesotho_sa_leboa", R.string.layout_sesotho_sa_leboa, "com.alpware.keymapkit.receiver.generated.SesothoSaLeboaLayoutReceiver", LayoutCategory.AFRICAN, false),
        KeyboardLayoutItem("setswana", R.string.layout_setswana, "com.alpware.keymapkit.receiver.generated.SetswanaLayoutReceiver", LayoutCategory.AFRICAN, false),
        KeyboardLayoutItem("sinhala", R.string.layout_sinhala, "com.alpware.keymapkit.receiver.generated.SinhalaLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("slovak_qwerty", R.string.layout_slovak_qwerty, "com.alpware.keymapkit.receiver.generated.SlovakQwertyLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("slovak_qwertz", R.string.layout_slovak_qwertz, "com.alpware.keymapkit.receiver.generated.SlovakQwertzLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("sorbian_extended", R.string.layout_sorbian_extended, "com.alpware.keymapkit.receiver.generated.SorbianExtendedLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("sorbian_standard", R.string.layout_sorbian_standard, "com.alpware.keymapkit.receiver.generated.SorbianStandardLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("spanish_variation", R.string.layout_spanish_variation, "com.alpware.keymapkit.receiver.generated.SpanishVariationLayoutReceiver", LayoutCategory.LATIN, true),
        KeyboardLayoutItem("swedish_dvorak_a1", R.string.layout_swedish_dvorak_a1, "com.alpware.keymapkit.receiver.generated.SwedishDvorakA1LayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("swedish_with_sami", R.string.layout_swedish_with_sami, "com.alpware.keymapkit.receiver.generated.SwedishWithSamiLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("syriac", R.string.layout_syriac, "com.alpware.keymapkit.receiver.generated.SyriacLayoutReceiver", LayoutCategory.SEMITIC, false),
        KeyboardLayoutItem("syriac_phonetic", R.string.layout_syriac_phonetic, "com.alpware.keymapkit.receiver.generated.SyriacPhoneticLayoutReceiver", LayoutCategory.SEMITIC, false),
        KeyboardLayoutItem("tajik", R.string.layout_tajik, "com.alpware.keymapkit.receiver.generated.TajikLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("tamil", R.string.layout_tamil, "com.alpware.keymapkit.receiver.generated.TamilLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("tamil99", R.string.layout_tamil99, "com.alpware.keymapkit.receiver.generated.Tamil99LayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("tatar", R.string.layout_tatar, "com.alpware.keymapkit.receiver.generated.TatarLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("telugu", R.string.layout_telugu, "com.alpware.keymapkit.receiver.generated.TeluguLayoutReceiver", LayoutCategory.INDIC, false),
        KeyboardLayoutItem("thai_kedmanee", R.string.layout_thai_kedmanee, "com.alpware.keymapkit.receiver.generated.ThaiKedmaneeLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_kedmanee_non_shiftlock", R.string.layout_thai_kedmanee_non_shiftlock, "com.alpware.keymapkit.receiver.generated.ThaiKedmaneeNonShiftlockLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_kedmanee_writer", R.string.layout_thai_kedmanee_writer, "com.alpware.keymapkit.receiver.generated.ThaiKedmaneeWriterLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_kedmanee_writer_non_shiftlock", R.string.layout_thai_kedmanee_writer_non_shiftlock, "com.alpware.keymapkit.receiver.generated.ThaiKedmaneeWriterNonShiftlockLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_manoonchai", R.string.layout_thai_manoonchai, "com.alpware.keymapkit.receiver.generated.ThaiManoonchaiLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_manoonchai_non_shiftlock", R.string.layout_thai_manoonchai_non_shiftlock, "com.alpware.keymapkit.receiver.generated.ThaiManoonchaiNonShiftlockLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_manoonchai_writer", R.string.layout_thai_manoonchai_writer, "com.alpware.keymapkit.receiver.generated.ThaiManoonchaiWriterLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_manoonchai_writer_non_shiftlock", R.string.layout_thai_manoonchai_writer_non_shiftlock, "com.alpware.keymapkit.receiver.generated.ThaiManoonchaiWriterNonShiftlockLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_pattachote", R.string.layout_thai_pattachote, "com.alpware.keymapkit.receiver.generated.ThaiPattachoteLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_pattachote_non_shiftlock", R.string.layout_thai_pattachote_non_shiftlock, "com.alpware.keymapkit.receiver.generated.ThaiPattachoteNonShiftlockLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_pattachote_writer", R.string.layout_thai_pattachote_writer, "com.alpware.keymapkit.receiver.generated.ThaiPattachoteWriterLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_pattachote_writer_non_shiftlock", R.string.layout_thai_pattachote_writer_non_shiftlock, "com.alpware.keymapkit.receiver.generated.ThaiPattachoteWriterNonShiftlockLayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("thai_tis_820_2538", R.string.layout_thai_tis_820_2538, "com.alpware.keymapkit.receiver.generated.ThaiTis8202538LayoutReceiver", LayoutCategory.ASIAN, false),
        KeyboardLayoutItem("tifinagh_basic", R.string.layout_tifinagh_basic, "com.alpware.keymapkit.receiver.generated.TifinaghBasicLayoutReceiver", LayoutCategory.AFRICAN, false),
        KeyboardLayoutItem("tifinagh_extended", R.string.layout_tifinagh_extended, "com.alpware.keymapkit.receiver.generated.TifinaghExtendedLayoutReceiver", LayoutCategory.AFRICAN, false),
        KeyboardLayoutItem("turkish_f", R.string.layout_turkish_f, "com.alpware.keymapkit.receiver.generated.TurkishFLayoutReceiver", LayoutCategory.LATIN, true),
        KeyboardLayoutItem("turkish_q", R.string.layout_turkish_q, "com.alpware.keymapkit.receiver.generated.TurkishQLayoutReceiver", LayoutCategory.LATIN, true),
        KeyboardLayoutItem("turkmen", R.string.layout_turkmen, "com.alpware.keymapkit.receiver.generated.TurkmenLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("ukrainian_enhanced", R.string.layout_ukrainian_enhanced, "com.alpware.keymapkit.receiver.generated.UkrainianEnhancedLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("united_kingdom_extended", R.string.layout_united_kingdom_extended, "com.alpware.keymapkit.receiver.generated.UnitedKingdomExtendedLayoutReceiver", LayoutCategory.LATIN, true),
        KeyboardLayoutItem("united_states_dvorak", R.string.layout_united_states_dvorak, "com.alpware.keymapkit.receiver.generated.UnitedStatesDvorakLayoutReceiver", LayoutCategory.LATIN, true),
        KeyboardLayoutItem("united_states_dvorak_for_left_hand", R.string.layout_united_states_dvorak_for_left_hand, "com.alpware.keymapkit.receiver.generated.UnitedStatesDvorakForLeftHandLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("united_states_dvorak_for_right_hand", R.string.layout_united_states_dvorak_for_right_hand, "com.alpware.keymapkit.receiver.generated.UnitedStatesDvorakForRightHandLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("united_states_dvorak_programmer", R.string.layout_united_states_dvorak_programmer, "com.alpware.keymapkit.receiver.generated.UnitedStatesDvorakProgrammerLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("urdu", R.string.layout_urdu, "com.alpware.keymapkit.receiver.generated.UrduLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("urdu_phonetic", R.string.layout_urdu_phonetic, "com.alpware.keymapkit.receiver.generated.UrduPhoneticLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("us_english_table_for_ibm_arabic_238_l", R.string.layout_us_english_table_for_ibm_arabic_238_l, "com.alpware.keymapkit.receiver.generated.UsEnglishTableForIbmArabic238LLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("uyghur", R.string.layout_uyghur, "com.alpware.keymapkit.receiver.generated.UyghurLayoutReceiver", LayoutCategory.ARABIC, false),
        KeyboardLayoutItem("uzbek_cyrillic", R.string.layout_uzbek_cyrillic, "com.alpware.keymapkit.receiver.generated.UzbekCyrillicLayoutReceiver", LayoutCategory.CYRILLIC, false),
        KeyboardLayoutItem("vietnamese", R.string.layout_vietnamese, "com.alpware.keymapkit.receiver.generated.VietnameseLayoutReceiver", LayoutCategory.LATIN, false),
        KeyboardLayoutItem("wolof", R.string.layout_wolof, "com.alpware.keymapkit.receiver.generated.WolofLayoutReceiver", LayoutCategory.AFRICAN, false),
    )

    fun byId(id: String): KeyboardLayoutItem? = all.firstOrNull { it.id == id }
}